n_prompt: "bad quality, worse quality"
vdm_prompt: "a man is standing in front of a window"
relight_prompt: "a man is standing in front of a window, warm sunlight through the window"
video_path: "input_cog/blackman.mp4"
light_radius: 150
bg_source: "SMI_CIRCULAR"

save_path: "output_cog"

width: 720
height: 480
num_frames: 49
strength: 0.4
gamma: 0.7
num_step: 25
text_guide_scale: 2
seed: 42