n_prompt: "bad quality, worse quality"
vdm_prompt: "an anime girl"
relight_prompt: "an anime girl, neon light"
video_path: "input_cog/girl2.mp4"
save_path: "output_cog"

width: 512
height: 512
num_frames: 16
strength: 0.4
gamma: 0.7
num_step: 25
text_guide_scale: 2
seed: 42